name: csst_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - numpy
  - scipy
  - matplotlib
  - pandas
  - qutip>=5.3
  - jupyterlab
  - ipykernel
  - tqdm
  - scikit-learn
  - statsmodels
  - networkx
  - threadpoolctl
  - pip
  - pylint
  - pip:  
    - matplotlib-label-lines

  
